/*
-- Création du USER SQL
alter session
set
    "_ORACLE_SCRIPT" = true;

CREATE USER "AMAZONDATABSE" IDENTIFIED BY "MDPAMAZONDATABSE";

ALTER USER "AMAZONDATABSE" DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "AMAZONDATABSE";

GRANT CREATE ANY INDEX TO "AMAZONDATABSE";

GRANT CREATE VIEW TO "AMAZONDATABSE";

GRANT CREATE SESSION TO "AMAZONDATABSE";

GRANT
SELECT
    ANY TABLE TO "AMAZONDATABSE";

GRANT DELETE ANY TABLE TO "AMAZONDATABSE";

GRANT CREATE TABLE TO "AMAZONDATABSE";

GRANT DROP ANY TABLE TO "AMAZONDATABSE";

GRANT UNDER ANY TYPE TO "AMAZONDATABSE";

GRANT CREATE TYPE TO "AMAZONDATABSE";

GRANT DROP ANY TYPE TO "AMAZONDATABSE";

GRANT EXECUTE ANY PROCEDURE TO "AMAZONDATABSE";

GRANT EXECUTE ANY PROGRAM TO "AMAZONDATABSE";

GRANT EXECUTE ANY TYPE TO "AMAZONDATABSE";

GRANT DROP ANY INDEX TO "AMAZONDATABSE";

GRANT
UPDATE
    ANY TABLE TO "AMAZONDATABSE";

GRANT DROP ANY VIEW TO "AMAZONDATABSE";

GRANT UNDER ANY VIEW TO "AMAZONDATABSE";

GRANT GRANT ANY PRIVILEGE TO "AMAZONDATABSE"; -- Crée la base de données AMAZON_DATABSE et ce connecter avec l'user configurer juste au dessus
*/

-- Drop toutes les tables
-- Drop all tables
BEGIN
    FOR table_rec IN (SELECT table_name FROM user_tables) LOOP
            EXECUTE IMMEDIATE 'DROP TABLE ' || table_rec.table_name || ' CASCADE CONSTRAINTS';
        END LOOP;
END;
/


-- Créé la table UTILISATEUR

CREATE TABLE "AMAZONDATABSE"."UTILISATEUR" 
(
    "UTILISATEUR_UID" VARCHAR2(200 BYTE) NOT NULL ENABLE,
	"UTILISATEUR_ID" NUMBER NOT NULL ENABLE, 
	"NOM" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"PRENOM" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"EST_VENDEUR" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"DATE_CREATION" DATE NOT NULL ENABLE, 
	"DATE_SUPRESSION" DATE, 
	 CONSTRAINT "UTILISATEUR_PK" PRIMARY KEY ("UTILISATEUR_UID")
	     USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255,
	 CONSTRAINT "UTILISATEUR_UK_EMAIL" UNIQUE ("EMAIL")
	     USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS ENABLE
);
-- creatiion des tables 
CREATE TABLE CONVERSATION
(
    CONVERSATION_UID VARCHAR2(255) NOT NULL,
    CONVERSATION_ID VARCHAR2(255) NOT NULL,
    COLUMN1 VARCHAR2(255) NOT NULL,
    CONSTRAINT CONVERSATION_PK PRIMARY KEY(CONVERSATION_UID) ENABLE
);

CREATE TABLE MESSAGE
(
  MESSAGE_UID VARCHAR2(255 BYTE) NOT NULL,
  MESSAGE_ID VARCHAR2(255 BYTE) NOT NULL,
  CONVERSATION_UID VARCHAR2(255 BYTE) NOT NULL,
  UTILISATEUR_DESTINATAIRE_UID VARCHAR2(255 BYTE) NOT NULL,
  UTILISATEUR_EXPEDITEUR_UID VARCHAR2(255 BYTE) NOT NULL,
  DATE_MESSAGE DATE NOT NULL,
  MESSAGE CLOB NOT NULL,
  CONSTRAINT MESSAGE_PK PRIMARY KEY (MESSAGE_UID),
  CONSTRAINT MESSAGE_FK_UTILISATEUR_EXPEDITEUR FOREIGN KEY (UTILISATEUR_EXPEDITEUR_UID)
    REFERENCES UTILISATEUR (UTILISATEUR_UID)
    ENABLE,
  CONSTRAINT MESSAGE_FK_UTILISATEUR_DESTINATAIRE FOREIGN KEY (UTILISATEUR_DESTINATAIRE_UID)
    REFERENCES UTILISATEUR (UTILISATEUR_UID)
    ENABLE
);

CREATE TABLE ADRESSE 
(
  ADRESSE_UID VARCHAR2(255) NOT NULL 
, ADRESSE_ID VARCHAR2(255) NOT NULL 
, ADRESSE_POSTALE VARCHAR2(255) NOT NULL 
, EST_FAVORITE NUMBER DEFAULT 0 NOT NULL 
, DATE_CREATION DATE NOT NULL 
, DATE_SUPPRESSION DATE 
, CONSTRAINT ADRESSE_PK PRIMARY KEY 
  (
    ADRESSE_UID 
  )
  ENABLE 
);

CREATE TABLE HISTORIQUE_ADRESSE
(
  HISTORIQUE_ADRESSE_UID VARCHAR2(255) NOT NULL,
  ID NUMBER NOT NULL,
  ADRESSE_INITIAL_UID VARCHAR2(255) NOT NULL,
  ADRESSE_UID VARCHAR2(255) NOT NULL,
  CONSTRAINT HISTORIQUE_ADRESSE_PK PRIMARY KEY (HISTORIQUE_ADRESSE_UID),
  CONSTRAINT HISTORIQUE_ADRESSE_FK1 FOREIGN KEY (ADRESSE_UID)
    REFERENCES ADRESSE (ADRESSE_UID)
    ENABLE,
  CONSTRAINT HISTORIQUE_ADRESSE_FK2 FOREIGN KEY (ADRESSE_INITIAL_UID)
    REFERENCES ADRESSE (ADRESSE_UID)
    ENABLE
);

CREATE TABLE COMMANDE
(
  COMMANDE_UID VARCHAR2(255) NOT NULL,
  COMMANDE_DATE DATE NOT NULL,
  UTILISATEUR_ACHETEUR_UID VARCHAR2(255) NOT NULL,
  UTILISATEUR_VENDEUR_UID VARCHAR2(255) NOT NULL,
  ADRESSE_EXPEDITION_UID VARCHAR2(255) NOT NULL,
  ADRESSE_DESTINANTION_UID VARCHAR2(255) NOT NULL,
  CONSTRAINT COMMANDE_PK PRIMARY KEY (COMMANDE_UID),
  CONSTRAINT COMMANDE_FK_ADRESSE_DESTINATION FOREIGN KEY (ADRESSE_DESTINANTION_UID)
    REFERENCES ADRESSE (ADRESSE_UID)
    ENABLE,
  CONSTRAINT COMMANDE_FK_ADRESSE_EXPEDITION FOREIGN KEY (ADRESSE_EXPEDITION_UID)
    REFERENCES ADRESSE (ADRESSE_UID)
    ENABLE,
  CONSTRAINT COMMANDE_FK_UTILISATEUR_ACHETEUR FOREIGN KEY (UTILISATEUR_ACHETEUR_UID)
    REFERENCES UTILISATEUR (UTILISATEUR_UID)
    ENABLE,
  CONSTRAINT COMMANDE_FK_UTILISATEUR_VENDEUR FOREIGN KEY (UTILISATEUR_VENDEUR_UID)
    REFERENCES UTILISATEUR (UTILISATEUR_UID)
    ENABLE
);

CREATE TABLE ARTICLE 
(
  ARTICLE_UID VARCHAR2(255) NOT NULL 
, ARTICLE_ID VARCHAR2(255) NOT NULL 
, ARTICLE_NOM VARCHAR2(255) NOT NULL 
, ARTICLE_DESCRIPTION VARCHAR2(255) NOT NULL 
, ARTICLE_PRIX NUMBER NOT NULL 
, ARTICLE_PHOTO VARCHAR2(255) NOT NULL 
, ARTICLE_NOTE NUMBER 
, ARTICLE_DATE_CREATION DATE NOT NULL 
, ARTICLE_DATE_SUPPRESSION DATE 
, CONSTRAINT ARTICLE_PK PRIMARY KEY 
  (
    ARTICLE_UID 
  )
  ENABLE 
);

CREATE TABLE CATEGORIE 
(
  CATEGORIE_ID VARCHAR2(255) NOT NULL 
, CATEGORIE_UID VARCHAR2(255) NOT NULL 
, CATEGORIE_NOM VARCHAR2(255) NOT NULL 
, CATEGORIE_DESCRIPTION CLOB NOT NULL 
, CONSTRAINT CATEGORIE_PK PRIMARY KEY 
  (
    CATEGORIE_ID 
  )
  ENABLE 
);

CREATE TABLE SOUHAITS 
(
  SOUHAITS_ID VARCHAR2(255) NOT NULL,
  SOUHAITS_UID VARCHAR2(255) NOT NULL,
  SOUHAITS_UTILISATEUR_UID VARCHAR2(255) NOT NULL,
  SOUHAITS_DATE_AJOUT DATE NOT NULL,
  SOUHAITS_DATE_SUPPRESSION DATE,  -- Correction du nom de la colonne
  SOUHAITS_COMMANDE_UID VARCHAR2(255),
  SOUHAITS_ARTICLE_UID VARCHAR2(255) NOT NULL,
  SOUHAITS_QUANTITÉ VARCHAR2(255),

  CONSTRAINT SOUHAITS_PK PRIMARY KEY (SOUHAITS_UID),

  CONSTRAINT SOUHAITS_ARTICLE_FK FOREIGN KEY (SOUHAITS_ARTICLE_UID)
    REFERENCES ARTICLE (ARTICLE_UID) ENABLE,
  CONSTRAINT SOUHAITS_COMMANDE_FK FOREIGN KEY (SOUHAITS_COMMANDE_UID)
    REFERENCES COMMANDE (COMMANDE_UID) ENABLE,
  CONSTRAINT SOUHAITS_UTILISATEUR_FK FOREIGN KEY (SOUHAITS_UTILISATEUR_UID)
    REFERENCES UTILISATEUR (UTILISATEUR_UID) ENABLE
);

CREATE TABLE COMMANDE_ARTICLE 
(
  COMMANDE_ARTICLE_UID VARCHAR2(255) NOT NULL,
  COMMANDE_ARTICLE_ID VARCHAR2(255) NOT NULL,
  COMMANDE_UID VARCHAR2(255) NOT NULL,
  QUANTITÉ NUMBER NOT NULL,
  COMMANDE_ARTICLE_ARTICLE_UID VARCHAR2(255) NOT NULL,

  CONSTRAINT COMMANDE_ARTICLE_PK PRIMARY KEY (COMMANDE_ARTICLE_UID),

  CONSTRAINT COMMANDE_ARTICLE_ARTICLE_FK FOREIGN KEY (COMMANDE_ARTICLE_ARTICLE_UID)
    REFERENCES ARTICLE (ARTICLE_UID) ENABLE,
  CONSTRAINT COMMANDE_ARTICLE_COMMANDE_FK FOREIGN KEY (COMMANDE_UID)
    REFERENCES COMMANDE (COMMANDE_UID) ENABLE
);


CREATE TABLE ARTICLE_CATEGORIE 
(
  ARTICLE_CATEGORIE_UID VARCHAR2(255) NOT NULL,
  ARTICLE_CATEGORIE_ID VARCHAR2(255) NOT NULL,
  ARTICLE_CATEGORIE_ARTICLE_UID VARCHAR2(20),
  ARTICLE_CATEGORIE_CATEGORIE_UID VARCHAR2(255) NOT NULL,

  CONSTRAINT ARTICLE_CATEGORIE_PK PRIMARY KEY (ARTICLE_CATEGORIE_UID),
  
  CONSTRAINT ARTICLE_CATEGORIE_ARTICLE_FK FOREIGN KEY (ARTICLE_CATEGORIE_ARTICLE_UID)
    REFERENCES ARTICLE (ARTICLE_UID),
  CONSTRAINT ARTICLE_CATEGORIE_CATEGORIE_FK FOREIGN KEY (ARTICLE_CATEGORIE_CATEGORIE_UID)
    REFERENCES CATEGORIE (CATEGORIE_ID)
);







